#pragma once

#include "Tree/HLD/HLD.hpp"
#include <vector>
#include <utility>


// 0: Vertex, 1: AddVertex, 2: AddEdge, 3: Rake, 4: Compress
template <typename G, typename DP>
struct StaticTopTree {
    using Path = typename DP::Path;
    using Point = typename DP::Point;
    struct Node {
        int l = -1, r = -1, p = -1, type = -1, v = -1;
        Path path; Point point;
    };
    int n, root_node;
    vector<Node> t;
    vector<int> pos;

    void _update(int i) {
        if(t[i].type == 0) t[i].path = DP::vertex(t[i].v);
        else if(t[i].type == 1) t[i].path = DP::add_vertex(t[t[i].l].point, t[i].v);
        else if(t[i].type == 2) t[i].point = DP::add_edge(t[t[i].l].path);
        else if(t[i].type == 3) t[i].point = DP::rake(t[t[i].l].point, t[t[i].r].point);
        else if(t[i].type == 4) t[i].path = DP::compress(t[t[i].l].path, t[t[i].r].path);
    }

    int _make(int type, int l = -1, int r = -1) {
        int i = t.size();
        t.push_back({l, r, -1, type, -1, {}, {}});
        if(l != -1) t[l].p = i;
        if(r != -1) t[r].p = i;
        return i;
    }

    // G の参照を受け取り、コンストラクタ内で HLDecomposition をインスタンス化
    StaticTopTree(G& g, int root = 0) : n(g.size()), pos(n, -1) {
        if(n == 0) return;
        t.reserve(4 * n);
        
        // --- ここで HLD を生成・構築 ---
        HLDecomposition<G> hld(g);
        hld.build(root);
        // -------------------------------

        auto build_tree = [&](auto& self, vector<pair<int, int>>& A, int l, int r, int type) -> int {
            if(l == r) return A[l].first;
            int sum = 0, cur = 0, mid = l, best = 2e9;
            for(int i = l; i <= r; i++) sum += A[i].second;
            for(int i = l; i < r; i++) {
                cur += A[i].second;
                int diff = abs(sum - cur * 2); // 左右の重みの差分
                if (diff < best) {
                    best = diff;
                    mid = i;
                } else {
                    break; // 差分が増加に転じたら（最適点を過ぎたら）即終了
                }
            }
            int u = _make(type, self(self, A, l, mid, type), self(self, A, mid + 1, r, type));
            _update(u);
            return u;
        };

        auto build_path = [&](auto& self, int u) -> int {
            vector<pair<int, int>> path;
            for(int curr = u; curr != -1; ) {
                int hc = -1, max_sz = 0;
                // コンストラクタ内で作られた hld を使用
                for(int nv : hld.g[curr]) {
                    if(nv != hld.par[curr] && hld.sz[nv] > max_sz) {
                        max_sz = hld.sz[nv]; hc = nv;
                    }
                }
                vector<pair<int, int>> lights;
                for(int nv : hld.g[curr]) {
                    if(nv != hld.par[curr] && nv != hc) {
                        int edge = _make(2, self(self, nv));
                        _update(edge);
                        lights.push_back({edge, hld.sz[nv]});
                    }
                }
                int node_u = _make(lights.empty() ? 0 : 1, lights.empty() ? -1 : build_tree(build_tree, lights, 0, lights.size() - 1, 3));
                t[node_u].v = curr; 
                _update(node_u);
                pos[curr] = node_u;
                path.push_back({node_u, hld.sz[curr] - (hc == -1 ? 0 : hld.sz[hc])});
                curr = hc;
            }
            return build_tree(build_tree, path, 0, path.size() - 1, 4);
        };
        
        root_node = build_path(build_path, root);
    }

    void update(int u) {
        for(int i = pos[u]; i != -1; i = t[i].p) _update(i);
    }

    Path query() const { return t[root_node].path; }
}; // generated by gemini